### PR TITLE
Added missing headers and removing some lines from Makefile.am

### PR DESCRIPTION
**Pull request by fdch**
Hi, 

Branch name is misleading since I doubt this fix is related to `macos` only. I added missing headers, following [this transition guideline](https://docs.opencv.org/3.1.0/db/dfa/tutorial_transition_guide.html).

Still, the objects I removed are bound to `opencv2/legacy` and need further revision.

These are the deleted lines from `src/Makefile.am`, for reference:

pix_opencv_backgroundsubtractor.h \
pix_opencv_blobtrack.h \
pix_opencv_calibration.h \
pix_opencv_findchessboardcorners.h \
pix_opencv_hu_compare.h \
pix_opencv_knear.h \
pix_opencv_lk.h \
pix_opencv_pgh_compare.h \

pix_opencv_lk.cc \
pix_opencv_hist_compare.cc \
pix_opencv_knear.cc \
pix_opencv_pgh_compare.cc \
pix_opencv_of_bm.cc \
pix_opencv_of_hs.cc \
pix_opencv_of_lk.cc \
pix_opencv_calibration.cc \
pix_opencv_findchessboardcorners.cc \
pix_opencv_blobtrack.cc \
pix_opencv_backgroundsubtractor.cc \

### CODE REVIEW

**Comment by fdch** [comment]
this solves #9 and probably #8

**Comment by avilleret** [comment]
did you check if your changes work on Linux / Windows ?

**Comment by fdch** [comment]
No, I am only checking on macos. I have some time now and will try to tidy up these changes and see how they work on Linux.

**Comment by avilleret** [comment]
this doesn't work with opencv4, since we are moving, I'm closing this because it is no more relevant

**Pull request closed without merging**
