### PR TITLE
Fix pix_opencv_contours crash

### PR DESCRIPTION
**Pull request by fdch**
This is a simple fix is built on top of macos-compile branch.

### CODE REVIEW

**Comment by fdch** [comment]
this solves #12

**Comment by avilleret** [comment]
could you rebase on opencv4 ?

**Comment by fdch** [comment]
Yes, I will.

**Comment by fdch** [comment]
I tried rebasing but I am stuck with my little git knowledge. If you have any tips, please share, otherwise I'll try to learn this as fast as I can. But, it might take a bit longer than I expected.

**Comment by avilleret** [comment]
By rebasing I mean merging the opencv4 branch into yours.

So basically you should first pull this branch and how to do that depends on which client you're using.
If you're on command line, you should do something like : 

    git remote add avilleret https://github.com/avilleret/pix_opencv
    git pull avilleret
    git checkout avilleret/opencv4
    git checkout fix-contours
    git merge opencv4

Then you might have some merging issues, and its always easier to fix them with a gui tool.
Once all of the merging conflicts are resolved you can commit and push to you fix-contours branch and then this PR will be automatically updated with the new commit.

**Comment by avilleret** [comment]
this PR is no more relevant

**Pull request closed without merging**
